import time
import random
from plyer import notification


interval =600  # 10 minutes

# List of different messages
messages = [
    "Hey Navi, I miss you",
    "YOU ARE SO FINE",
    "I love YOU",
    "Sending hugs your way",
    "You make my heart happy",
    "Je t'aime (French)",
    "Te amo (Spanish)",
    "Ich liebe dich (German)",
    "Ti amo (Italian)",
    "Eu te amo (Portuguese)",
    "Aishiteru (Japanese)",
    "Saranghae (Korean)",
    "Ya lyublyu tebya (Russian)",
    "Te iubesc (Romanian)",
    "S'agapo (Greek)",
    "Aku cinta kamu (Indonesian)",
    "Mahal kita (Filipino)",
    "Ik hou van jou (Dutch)",
    "Ngiyakuthanda (Zulu)",
    "Main tumse pyaar karta hoon (Hindi)",
    "Ami tomake bhalobashi (Bengali)",
    "Naan unnai kathalikiraen (Tamil)",
    "Nenu ninnu premisthunnanu (Telugu)",
    "Naanu ninna preetisuttane (Kannada)",
    "Njan ninne snehikkunnu (Malayalam)",
    "Hu tane prem karu chu (Gujarati)",
    "Main tenu pyaar karda haan (Punjabi)",
    "Mi tuzhyavar prem karto (Marathi)",
    "Mu tumaku bhala paye (Odia)",
    "Moi tomak bhal pau (Assamese)",
    "Ami tomake bhalobashi (Sylheti)",
    "Hu tanne pyaar kanda haan (Sindhi)",
    "You're the best EVER.",
    "Just a little reminder that you’re loved DUH",
    "Thinking about you today",
    "Wishing you an amazing day",
    "You're on my mind right now",
    "Hope today treats you well",
    "Stay strong, you're incredible",
    "You make my days better",
    "I appreciate you more than you know",
    "Take a deep breath and relax",
    "You're doing amazing things",
    "Just wanted to check in on you",
    "I hope you're feeling great",
    "You're the best part of my day",
    "No one compares to you",
    "Your presence makes everything better",
    "I admire you so much",
    "You're absolutely incredible",
    "You deserve the best",
    "Stay confident, you're amazing",
    "Your kindness is unmatched",
    "Life is better with you around",
    "You bring so much joy",
    "I can't stop thinking about you",
    "You're worth everything",
    "You're doing better than you think",
    "You make life brighter",
    "Keep being your awesome self",
    "You’re important to me",
    "I hope you’re smiling right now",
    "Wishing you all the happiness",
    "You're one of a kind",
    "Every moment with you is special",
    "You're always on my mind",
    "You inspire me daily",
    "You're stronger than you realize",
    "Never forget how amazing you are",
    "I believe in you, always",
    "You're truly unforgettable",
    "You’re worth every effort",
    "Hope today brings you joy",
    "You make everything better",
    "You're a blessing in my life",
    "No one shines like you do",
    "You’re perfect just the way you are",
    "I'm grateful for you",
    "You're always in my thoughts",
    "You light up my world",
    "I appreciate you endlessly",
    "You're capable of anything",
    "You're a dream come true",
    "You're beyond special to me",
    "Everything feels right with you",
    "You're the reason for my smiles",
    "You deserve all the good things",
    "You're irreplaceable",
    "I'm so lucky to know you",
    "You're a beautiful soul",
    "You're truly one of a kind",
    "Your energy is magnetic",
    "Your happiness matters to me",
    "You're an absolute treasure",
    "You're simply the best",
    "I'm always here for you",
    "You're my favorite person",
    "You're a ray of sunshine",
    "Your presence is comforting",
    "You're a masterpiece",
    "The world is better with you in it",
    "You're beyond amazing",
    "You're incredibly special",
    "You're my favorite part of the day",
    "You're someone worth cherishing",
    "You're doing great, keep going",
    "You bring so much light",
    "I appreciate everything about you",
    "You're a beautiful person inside and out",
    "You're unforgettable in the best way",
    "I'm thinking about you right now",
    "You're a blessing I never expected",
    "Your impact is greater than you know",
    "You're a source of happiness",
    "Your energy is unmatched",
    "You're worth every moment",
    "You're doing better than you think",
    "I hope you’re taking care of yourself",
    "You're a wonderful human being",
    "You're my favorite thought",
    "You're genuinely special",
    "You’re always in my heart",
    "You is everything",
    "You're more than enough",
    "You're a beautiful presence in my life",
    "You deserve all the happiness",
    "I admire everything about you",
    "You’re beyond words amazing",
    "I hope you feel loved today",
    "You're simply wonderful",
]

while True:

    # Pick a random message
    message = random.choice(messages)

    # Send the notification
    notification.notify(
        title="💖 Love Reminder 💖",
        message=message,
        app_name="Love Notifier",
        timeout=10
    )

    # Wait before the next notification
    time.sleep(interval)